services:
  mysql:
    container_name: 'picpay-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=picpaydb'
      - 'MYSQL_PASSWORD=picpay123'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'